### ISSUE TITLE
Make general connection object

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pvsite-datamodel#10]
## Detailed Description
Good to make a generation connection where a sessions can be made

## Context
Good to have this for the forecaster, and the api, and anything else that connection to the database

## Possible Implementation
Similar to https://github.com/openclimatefix/nowcasting_datamodel/blob/main/nowcasting_datamodel/connection.py (dont need make partitions yet)
- Good to have tests aswell for this

**Comment by devsjc** [comment]
Added without tests https://github.com/openclimatefix/pvsite-datamodel/commit/ae113fffedd5f1dc8a993f9ba15ba19825210fdb

**Comment by devsjc** [comment]
Tested with https://github.com/openclimatefix/pvsite-datamodel/commit/451d1ffdf1f2ac700aacb803f18e355fb2c531e5
