### ISSUE TITLE
Add pv id to pv metadata table

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pvsite-datamodel#11]
Extra requirement to add a `pv_id` to the table. Keep the `uuid` as well. This is because the ML guys want an `id`, i.e 1 to 10,000 that they can use to train the model with. The `uuid` will be harder work to train with.

**Comment by devsjc** [comment]
Without knowing anything about the ML situation, are the ML guys not able to pull the sites and then assign an integer pv_id to that data based on sorting by createdtime or whatever?

**Comment by peterdudfield** [comment]
> Without knowing anything about the ML situation, are the ML guys not able to pull the sites and then assign an integer pv_id to that data based on sorting by createdtime or whatever?

they could, but they need to be unique and its easier if they start at 1. Essentially its just row number. I thought in the passed having some csv that does this, but I think database is the real solution

**Comment by devsjc** [comment]
Will they be pulling this data using the functions that are yet to be written in the datamodel? If that's the case, it could then just be a matter of adding that functionality as a mapping into the read function they use, something like [this].(https://trinket.io/python3/6fad4faedc?runOption=run&start=result)

I'm not saying we shouldn't just add the column to the database necessarily, but I think it's worth raising the discussion on decoupling the data we store and its format vs what is wanted for analysis - does this table exist for our ML guys, or for clients using the API?

**Comment by peterdudfield** [comment]
The table doesnt exits yet. The `id` hasnt bee used yet, but it will in the future, so trying to build for that. 

Yea could do it when we create, but not sure how this would work for example if we only load the `passiv` sites compared to loading `passiv` and `client_1` sites. 

Is it not simplist to just add `pv_id` in the database? Less mitakes that way and very clear what it is. could be `ml_id` as you suggest

**Comment by devsjc** [comment]
In that use case then yes, it makes sense to add the column. I only mention this now because I think its a good idea in general to have your datamodels in bounded contexts, so you can more readily decouple services; I think it's a useful paradigm to keep in mind!

**Comment by devsjc** [comment]
Added with https://github.com/openclimatefix/pvsite-datamodel/commit/ae113fffedd5f1dc8a993f9ba15ba19825210fdb

**Comment by peterdudfield** [comment]
thanks
