### ISSUE TITLE
Make sqlalamcy models

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pvsite-datamodel#2]
## Detailed Description
Using .sql file, make the sqlalmacy models

## Context
.sql file is made from .dbml

## Possible Implementation
Using this [blog](https://xnuinside.medium.com/code-generation-how-to-generate-pydantic-sqlalchemy-ginoorm-models-from-sql-ddl-2c111b08b7a7) we can change raw sql into sqlalacmy models. We might have to tweak them a bit

**Comment by peterdudfield** [comment]
This got merged, so real's should work now
- https://github.com/xnuinside/omymodels/pull/44#event-8175375080

**Comment by devsjc** [comment]
Done with https://github.com/openclimatefix/pvsite-datamodel/commit/ae113fffedd5f1dc8a993f9ba15ba19825210fdb
