### ISSUE TITLE
Setup terraform for new database

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pvsite-datamodel#3]
## Detailed Description
Set up rds database in aws using terraform

## Context
- good to do random password and save to secrets too
- might need to give it a vpc_id, rather than make a new one
- might be good to setup a new repo for this
- might be good to move api terraform code there too - [here](https://github.com/openclimatefix/PVSiteAPI)

## Possible Implementation
See code in [here](https://github.com/openclimatefix/nowcasting_infrastructure/tree/main/terraform/modules/database). This makes
- IAM roles
- RDS database
- Secrets
- Security groups

**Comment by devsjc** [comment]
Created MR here for modifying the module https://github.com/openclimatefix/nowcasting_infrastructure/pull/150

**Comment by devsjc** [comment]
Created new MR refactoring code into domain subfolders, and updating the database module https://github.com/openclimatefix/ocf-infrastructure/pull/151

**Comment by devsjc** [comment]
Closed with https://github.com/openclimatefix/ocf-infrastructure/pull/151
