### ISSUE TITLE
add timedelta option to write

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pvsite-datamodel#41]
## Detailed Description
When writing the to the database [here](https://github.com/openclimatefix/pvsite-datamodel/blob/main/sdk/python/pvsite_datamodel/write/forecast.py#L18), have option to pass in a timedelta, e.g 15 mins. The deafult one is set to 5. 

You may have to upgrade [this](https://github.com/openclimatefix/pvsite-datamodel/blob/main/sdk/python/pvsite_datamodel/write/datetime_intervals.py#L13) function too

**Comment by simlmx** [comment]
Added and end date on top of the start_date (which is what the model returns currently).
I didn't have to change `get_or_else_create_datetime_interval`.
