### ISSUE TITLE
Make write functions

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pvsite-datamodel#7]
## Detailed Description
1. Write function for a forecast
2. Write function for PV data

## Context
Good to have generic write function, which can save to many tables, but the thing doing the writing doesnt need to know about

## Possible Implementation
1. Write Forecasts, One write to the `Forecast` and `forecast_value` table and writes to the `forecast_value_latest` table, being upserting.
2. Add a `PV site`
3. Update a `PV site`
4. Add a `PV Generation` value
TODO defined inputs to these objects

**Comment by peterdudfield** [comment]
The input to save the forecast could be a list if dataframes. Each of the dataframes will have
- "target_datetime_utc"
- "forecast_kw"
- "pv_uuid" 

This will keep things in dataframes in the forecaster, which is handy. 

we could use https://pandera.readthedocs.io/en/stable/ to ensure the dataframes have the correct columns

**Comment by peterdudfield** [comment]
Would we be able to add an option where we pass `ml_id` instead of `pv_uuid` This would keep the old database cleaner - https://github.com/openclimatefix/nowcasting_datamodel/issues/140

**Comment by devsjc** [comment]
So the dataframe could either be 

    "target_datetime_utc"
    "forecast_kw"
    "pv_uuid"

Or
 
    "target_datetime_utc"
    "forecast_kw"
    "pv_ml_id"

for instance?

**Comment by peterdudfield** [comment]
yea, that would be great
